import 'package:flutter/material.dart';
import '../services/erp_store.dart';
import '../widgets/theme.dart';

class ErpPosScreen extends StatefulWidget{
  final ErpStore erp;
  const ErpPosScreen({super.key,required this.erp});
  @override State<ErpPosScreen> createState()=>_ErpPosScreenState();
}
class _ErpPosScreenState extends State<ErpPosScreen>{
  final Map<String,double> cart={};String customerId='';String q='';
  @override void initState(){super.initState();if(widget.erp.customers.isNotEmpty)customerId=widget.erp.customers.first.id;}
  @override Widget build(BuildContext context){
    final products=widget.erp.products.where((p)=>p.stock>0&&(q.isEmpty||p.name.toLowerCase().contains(q.toLowerCase())||p.sku.toLowerCase().contains(q.toLowerCase()))).toList();
    final lines=cart.entries.map((e){final p=widget.erp.product(e.key)!;return ErpLine(productId:p.id,name:p.name,qty:e.value,price:p.price,cost:p.cost);}).toList();final total=lines.fold<double>(0,(s,l)=>s+l.total);
    final wide=MediaQuery.sizeOf(context).width>780;
    final productsPane=_products(products);final cartPane=_cart(lines,total);
    return Padding(padding:const EdgeInsets.all(14),child:wide?Row(children:[Expanded(flex:3,child:productsPane),const SizedBox(width:12),SizedBox(width:330,child:cartPane)]):Column(children:[Expanded(child:productsPane),const SizedBox(height:8),SizedBox(height:270,child:cartPane)]));
  }
  Widget _products(List<ErpProduct> products)=>Column(children:[Row(children:[const Expanded(child:Text('نقطة البيع POS',style:TextStyle(fontWeight:FontWeight.w900,fontSize:23,color:darkText))),tag('جلسة مفتوحة',creditColor)]),const SizedBox(height:10),TextField(onChanged:(v)=>setState(()=>q=v),decoration:fieldDec('بحث / باركود',Icons.qr_code_scanner_rounded)),const SizedBox(height:10),Expanded(child:LayoutBuilder(builder:(context,c){final cols=c.maxWidth>700?4:c.maxWidth>470?3:2;return GridView.builder(gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:cols,crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:1.12),itemCount:products.length,itemBuilder:(context,i){final p=products[i];return InkWell(onTap:()=>setState(()=>cart[p.id]=(cart[p.id]??0)+1),borderRadius:BorderRadius.circular(18),child:Container(padding:const EdgeInsets.all(12),decoration:softCard(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:primaryLight,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.inventory_2_outlined,color:primary)),const Spacer(),Text(p.name,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900)),Text(money(p.price),style:const TextStyle(color:primaryDark,fontWeight:FontWeight.w900,fontSize:17)),Text('متاح ${money(p.stock)}',style:const TextStyle(color:softText,fontSize:9.5))])));});}))]);
  Widget _cart(List<ErpLine> lines,double total)=>Container(padding:const EdgeInsets.all(14),decoration:softCard(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('سلة البيع',style:TextStyle(fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:8),if(widget.erp.customers.isNotEmpty)DropdownButtonFormField<String>(initialValue:customerId.isEmpty?null:customerId,isExpanded:true,decoration:const InputDecoration(labelText:'العميل',isDense:true),items:widget.erp.customers.map((e)=>DropdownMenuItem(value:e.id,child:Text(e.name))).toList(),onChanged:(v)=>setState(()=>customerId=v??'')),const SizedBox(height:8),Expanded(child:lines.isEmpty?Center(child:Text('اضغط على منتج لإضافته',style:TextStyle(color:softText.withOpacity(.8),fontWeight:FontWeight.w700))):ListView(children:lines.map((l)=>ListTile(dense:true,contentPadding:EdgeInsets.zero,title:Text(l.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${money(l.qty)} × ${money(l.price)}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text(money(l.total),style:const TextStyle(fontWeight:FontWeight.w900)),IconButton(icon:const Icon(Icons.remove_circle_outline_rounded,color:coral),onPressed:()=>setState((){final n=(cart[l.productId]??1)-1;if(n<=0){cart.remove(l.productId);}else{cart[l.productId]=n;}}))])).toList())),const Divider(),Row(children:[const Text('الإجمالي',style:TextStyle(fontWeight:FontWeight.w900)),const Spacer(),Text(money(total),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:21,color:primaryDark))]),const SizedBox(height:8),FilledButton.icon(onPressed:lines.isEmpty||customerId.isEmpty?null:()async{try{await widget.erp.createSale(customerId:customerId,lines:lines,paid:total);if(mounted){setState(()=>cart.clear());ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تمت عملية البيع بنجاح')));}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}},icon:const Icon(Icons.payments_rounded),label:const Text('دفع وإتمام البيع'),style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(46))) ]));
}
